/**
 * verify-prompt-hashes.ts
 *
 * Computes SHA256 of each file in frontend/lib/agents/prompts/ and compares
 * against the hardcoded manifest below.
 *
 * Exit codes:
 *   0 — all hashes match
 *   1 — one or more hashes mismatch or file missing
 *
 * Usage:
 *   npm run verify-prompts
 *
 * To regenerate the manifest after intentional prompt changes:
 *   npm run verify-prompts -- --update
 *   (prints new manifest — copy it into EXPECTED_HASHES below)
 *
 * If a hash mismatch is detected in CI, it means a prompt was edited without
 * updating the manifest. To update:
 *   1. Review the diff carefully
 *   2. Add a CONTEXT §14 Decisions Log entry documenting the change
 *   3. Run `npm run verify-prompts -- --update` and paste the output here
 */

import { createHash } from "crypto";
import { readdirSync, readFileSync } from "fs";
import { join, resolve } from "path";

const PROMPTS_DIR = resolve(__dirname, "../lib/agents/prompts");

/**
 * Hardcoded manifest of expected SHA256 hashes.
 * Generated by running: npm run verify-prompts -- --update
 *
 * DO NOT edit these manually — run the update command above.
 */
const EXPECTED_HASHES: Record<string, string> = {
  "fundamental.md": "ba2370d6aa1f6bb0e3adc3e639580b190dc2946d6c410ad2b3080446ec50f8b4",
  "portfolio_decision.md": "1296e663f38f7307d5399720d8db56a3494dcf9cb0519017984e47f4eb01a629",
  "sentiment.md": "a564b2caad9299fdae7a33287259dc78c1e66df65ea9178a9ff48572458bc494",
  "synthesis.md": "9fc6d3330a8f9ed09e4dea4af11ef91bacde567ea51016575d00dfe5f5abbc95",
  "technical.md": "f94cafdf4546e0ac9528e23991da6ef4ef36215fd0d6754f770c8501227f0250",
};

function sha256File(filePath: string): string {
  const content = readFileSync(filePath);
  return createHash("sha256").update(content).digest("hex");
}

function getPromptFiles(): string[] {
  return readdirSync(PROMPTS_DIR)
    .filter((f) => f.endsWith(".md"))
    .sort();
}

function computeCurrentHashes(): Record<string, string> {
  const hashes: Record<string, string> = {};
  for (const file of getPromptFiles()) {
    const filePath = join(PROMPTS_DIR, file);
    hashes[file] = sha256File(filePath);
  }
  return hashes;
}

const isUpdate = process.argv.includes("--update");

const currentHashes = computeCurrentHashes();

if (isUpdate) {
  // Print new manifest for copy-paste into EXPECTED_HASHES
  console.log("Current prompt hashes (copy into EXPECTED_HASHES):");
  console.log("{");
  for (const [file, hash] of Object.entries(currentHashes)) {
    console.log(`  "${file}": "${hash}",`);
  }
  console.log("}");
  process.exit(0);
}

// Verify all expected files exist and hashes match
let failed = false;

for (const [file, expectedHash] of Object.entries(EXPECTED_HASHES)) {
  const currentHash = currentHashes[file];

  if (currentHash === undefined) {
    console.error(`MISSING: ${file} — expected hash ${expectedHash}`);
    failed = true;
    continue;
  }

  if (currentHash !== expectedHash) {
    console.error(
      `MISMATCH: ${file}\n  expected: ${expectedHash}\n  actual:   ${currentHash}`,
    );
    failed = true;
  } else {
    console.log(`OK: ${file}`);
  }
}

// Check for unexpected new files not in manifest
for (const file of Object.keys(currentHashes)) {
  if (!(file in EXPECTED_HASHES)) {
    console.warn(
      `NEW FILE: ${file} (hash: ${currentHashes[file]}) — add to manifest`,
    );
    failed = true;
  }
}

if (failed) {
  console.error(
    "\nPrompt hash verification FAILED. " +
      "Run `npm run verify-prompts -- --update` to regenerate the manifest.",
  );
  process.exit(1);
}

console.log("\nAll prompt hashes verified successfully.");
process.exit(0);
